Task#1: Compute 4 x4 matrix computation, e.g. addition, subtraction, multiplication and division.

In [4]:
import numpy as np

matrix1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

matrix2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])




In [6]:
# Matrix Multiplication
multi_matrix = matrix1 * matrix2
print(multi_matrix)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]


In [7]:
# Matrix Addition
add_matrix = matrix1 + matrix2
print(add_matrix)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [8]:
# Matrix Subtraction
sub_matrix = matrix1 - matrix2
print(sub_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
# Matrix Division
div_matrix = matrix1 / matrix2
print(div_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
